import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { AiAutoApplyPayload, AiJobIntelligencePayload, AiPortfolioPayload } from "@/lib/queue/types";

function extractTerms(text: string, terms: string[]) {
  const lower = text.toLowerCase();
  return terms.filter((term) => lower.includes(term.toLowerCase()));
}

export async function handleJobIntelligence(payload: AiJobIntelligencePayload) {
  await prisma.job.update({
    where: { id: payload.jobRecordId },
    data: { status: "processing", attempts: { increment: 1 }, lastError: null },
  });

  const skills = extractTerms(payload.jobDescription, ["React", "Next.js", "TypeScript", "Accessibility", "Performance", "PostgreSQL", "Prisma"]);
  const tools = extractTerms(payload.jobDescription, ["BullMQ", "Figma", "Datadog", "Vercel", "Sentry", "Recharts"]);
  const missing = ["GraphQL", "LLM evaluation", "payments domain"].filter((term) => !payload.jobDescription.toLowerCase().includes(term.toLowerCase()));
  const matchScore = Math.min(96, 64 + skills.length * 5 + tools.length * 3);

  const result = {
    skills,
    tools,
    experience: ["Product engineering", "Reusable UI systems", "Performance ownership"],
    missingSkills: missing,
    matchScore,
    schemaVersion: "job-intelligence.v1",
  };

  const opportunity = await prisma.jobOpportunity.create({
    data: {
      userId: payload.userId,
      company: "Imported JD",
      role: "Target Role",
      description: payload.jobDescription,
      matchScore,
      parsed: result as Prisma.InputJsonValue,
    },
  });

  await prisma.job.update({
    where: { id: payload.jobRecordId },
    data: {
      status: "completed",
      completedAt: new Date(),
      payload: { ...payload, result, jobOpportunityId: opportunity.id } as Prisma.InputJsonValue,
    },
  });

  return result;
}

export async function handleAutoApply(payload: AiAutoApplyPayload) {
  await prisma.job.update({
    where: { id: payload.jobRecordId },
    data: { status: "processing", attempts: { increment: 1 }, lastError: null },
  });

  const application = await prisma.application.create({
    data: {
      userId: payload.userId,
      resumeId: payload.resumeId,
      jobOpportunityId: payload.jobOpportunityId,
      company: "Queued Company",
      role: "Queued Role",
      matchScore: 88,
      generatedResume: payload.preview ?? "Generated resume will be attached by the AI worker.",
      coverLetter: "Structured cover letter draft generated by the queue-backed AI workflow.",
      emailDraft: "Structured hiring-manager email draft generated by the queue-backed AI workflow.",
      appliedAt: new Date(),
    },
  });

  await prisma.job.update({
    where: { id: payload.jobRecordId },
    data: {
      status: "completed",
      completedAt: new Date(),
      payload: { ...payload, applicationId: application.id } as Prisma.InputJsonValue,
    },
  });

  return { applicationId: application.id };
}

export async function handlePortfolio(payload: AiPortfolioPayload) {
  await prisma.job.update({
    where: { id: payload.jobRecordId },
    data: { status: "processing", attempts: { increment: 1 }, lastError: null },
  });

  const result = {
    theme: payload.theme,
    draftUrl: "https://aamir.resumeai.site",
    sections: ["Hero", "Projects", "Proof", "Contact"],
    schemaVersion: "portfolio.v1",
  };

  await prisma.job.update({
    where: { id: payload.jobRecordId },
    data: {
      status: "completed",
      completedAt: new Date(),
      payload: { ...payload, result } as Prisma.InputJsonValue,
    },
  });

  return result;
}
