/**
 * lib/agent/memory.ts
 *
 * Persistent memory layer for the Autonomous Career Agent.
 * Synchronizes working memory with `CareerTwin`, `TwinMemory`, and `CareerMemory`.
 * Performs vector-similarity search when possible, with keyword fallback.
 */

import { prisma } from "@/lib/db/prisma";
import { memoryService } from "@/lib/services/memory.service";
import { logger } from "@/lib/logger";
import type { AgentMemoryItem } from "./types";
import { TwinMemoryType } from "@prisma/client";

export class AgentMemory {
  /**
   * Retrieves or initializes the CareerTwin for a user.
   */
  static async getOrCreateTwin(userId: string) {
    const existing = await prisma.careerTwin.findUnique({
      where: { userId },
    });

    if (existing) {
      return existing;
    }

    // Create a new twin with default configurations
    const twin = await prisma.careerTwin.create({
      data: {
        userId,
        displayName: "AI Career Twin",
        status: "learning",
        autonomyMode: "assisted",
        professionalIdentity: {},
        cognitiveProfile: {
          learningStyle: "practical",
          focusDepth: 0.8,
        },
        scores: {
          readiness: 0.1,
          marketability: 0.1,
        },
        confidence: 0.5,
        strengths: [],
        weaknesses: [],
        bestFitRoles: [],
        hiddenOpportunities: [],
        salaryProjection: {},
        activePlan: {},
        privacyControls: {
          allowSharing: false,
          allowTelemetry: true,
        },
      },
    });

    // Log twin creation event
    await prisma.twinEvent.create({
      data: {
        twinId: twin.id,
        userId,
        type: "created",
        source: "agent_planner",
        summary: "AI Career Twin initialized.",
        payload: { autogenerated: true },
      },
    });

    return twin;
  }

  /**
   * Adds an item to the persistent memory (both CareerMemory and TwinMemory).
   */
  static async addMemory(
    userId: string,
    memory: {
      type: TwinMemoryType;
      title: string;
      content: string;
      importance?: number;
      confidence?: number;
      metadata?: Record<string, any>;
    }
  ): Promise<void> {
    try {
      const twin = await this.getOrCreateTwin(userId);
      const importance = memory.importance ?? 0.5;
      const confidence = memory.confidence ?? 0.8;
      const metadata = memory.metadata ?? {};

      // 1. Save to TwinMemory (requires pgvector raw SQL handling or fallback if vector fails)
      // Since prisma doesn't support vector directly, we use executeRaw or memoryService helpers.
      let embedding: number[] | null = null;
      try {
        embedding = await memoryService.embedText(`${memory.title}: ${memory.content}`);
      } catch (err) {
        logger.warn({ err, userId }, "[AgentMemory] Embedding failed — storing memory without vector.");
      }

      const memoryId = crypto.randomUUID();

      if (embedding) {
        const vectorLiteral = `[${embedding.join(",")}]`;
        await prisma.$executeRaw`
          INSERT INTO "TwinMemory" (
            id, "twinId", "userId", type, title, content, summary, source,
            "evidenceRefs", "semanticLinks", importance, confidence, "recencyWeight",
            "reinforcementCount", "accessScope", metadata, embedding, "createdAt", "updatedAt"
          ) VALUES (
            ${memoryId}::uuid,
            ${twin.id}::uuid,
            ${userId}::uuid,
            ${memory.type}::"TwinMemoryType",
            ${memory.title},
            ${memory.content},
            ${memory.content.slice(0, 200)},
            'agent',
            ARRAY[]::text[],
            '[]'::jsonb,
            ${importance},
            ${confidence},
            1.0,
            0,
            'private',
            ${JSON.stringify(metadata)}::jsonb,
            ${vectorLiteral}::vector,
            NOW(),
            NOW()
          )
        `;
      } else {
        await prisma.$executeRaw`
          INSERT INTO "TwinMemory" (
            id, "twinId", "userId", type, title, content, summary, source,
            "evidenceRefs", "semanticLinks", importance, confidence, "recencyWeight",
            "reinforcementCount", "accessScope", metadata, "createdAt", "updatedAt"
          ) VALUES (
            ${memoryId}::uuid,
            ${twin.id}::uuid,
            ${userId}::uuid,
            ${memory.type}::"TwinMemoryType",
            ${memory.title},
            ${memory.content},
            ${memory.content.slice(0, 200)},
            'agent',
            ARRAY[]::text[],
            '[]'::jsonb,
            ${importance},
            ${confidence},
            1.0,
            0,
            'private',
            ${JSON.stringify(metadata)}::jsonb,
            NOW(),
            NOW()
          )
        `;
      }

      // 2. Also save to CareerMemory for general platform use
      await memoryService.upsertMemory(userId, {
        type: this.mapTwinToCareerMemoryType(memory.type),
        title: memory.title,
        content: memory.content,
        source: "agent",
        confidence,
        metadata,
      });

      // 3. Log a twin event
      await prisma.twinEvent.create({
        data: {
          twinId: twin.id,
          userId,
          type: "memory_added",
          source: "agent_planner",
          summary: `Added ${memory.type} memory: "${memory.title}"`,
          payload: { memoryId },
        },
      });

      logger.info({ userId, type: memory.type }, "[AgentMemory] Successfully saved memory.");
    } catch (err) {
      logger.error({ err, userId }, "[AgentMemory] Failed to save memory");
    }
  }

  /**
   * Performs semantic/keyword search over TwinMemory.
   */
  static async searchMemories(
    userId: string,
    query: string,
    limit = 5
  ): Promise<AgentMemoryItem[]> {
    try {
      let embedding: number[] | null = null;
      try {
        embedding = await memoryService.embedText(query);
      } catch (err) {
        logger.warn({ err }, "[AgentMemory] Search embedding failed — falling back to text search");
      }

      if (embedding) {
        const vectorLiteral = `[${embedding.join(",")}]`;
        const rows = await prisma.$queryRaw<any[]>`
          SELECT
            id,
            type,
            title,
            content,
            importance,
            confidence,
            metadata,
            "createdAt"
          FROM "TwinMemory"
          WHERE "userId" = ${userId}::uuid
            AND embedding IS NOT NULL
          ORDER BY embedding <=> ${vectorLiteral}::vector
          LIMIT ${limit}
        `;
        return rows.map((r) => ({
          id: r.id,
          type: String(r.type),
          title: r.title,
          content: r.content,
          importance: Number(r.importance),
          confidence: Number(r.confidence),
          metadata: r.metadata ?? {},
          createdAt: r.createdAt.toISOString(),
        }));
      }

      // Keyword search fallback
      const fallbackRows = await prisma.twinMemory.findMany({
        where: {
          userId,
          OR: [
            { title: { contains: query, mode: "insensitive" } },
            { content: { contains: query, mode: "insensitive" } },
          ],
        },
        take: limit,
        orderBy: { importance: "desc" },
      });

      return fallbackRows.map((r) => ({
        id: r.id,
        type: String(r.type),
        title: r.title,
        content: r.content,
        importance: r.importance,
        confidence: r.confidence,
        metadata: (r.metadata as Record<string, any>) ?? {},
        createdAt: r.createdAt.toISOString(),
      }));
    } catch (err) {
      logger.error({ err, userId }, "[AgentMemory] Search memories failed");
      return [];
    }
  }

  /**
   * Retrieves user context (skills, experience, resume summaries) to build the prompt context.
   */
  static async retrieveUserContext(userId: string): Promise<{
    headline: string;
    summary: string;
    skills: string[];
    experience: Array<{ title: string; company: string; description: string }>;
    goals: Record<string, any>;
    education: string[];
  }> {
    const profile = await prisma.careerProfile.findUnique({
      where: { userId },
    });

    const activeResume = await prisma.resume.findFirst({
      where: { userId },
      orderBy: { updatedAt: "desc" },
    });

    const resumeData = (activeResume?.data as Record<string, any>) ?? {};

    const skills = (resumeData.skills as string[]) ?? [];
    const experience = ((resumeData.experience as any[]) ?? []).map((exp) => ({
      title: String(exp.title ?? exp.role ?? ""),
      company: String(exp.company ?? ""),
      description: String(exp.description ?? exp.points ?? ""),
    }));
    const education = ((resumeData.education as any[]) ?? []).map(
      (edu) => `${edu.degree} @ ${edu.school}`
    );

    return {
      headline: profile?.headline ?? activeResume?.title ?? "CareerOS User",
      summary: profile?.summary ?? (resumeData.personal?.summary as string) ?? "",
      skills,
      experience,
      goals: (profile?.goals as Record<string, any>) ?? {},
      education,
    };
  }

  private static mapTwinToCareerMemoryType(
    type: TwinMemoryType
  ): "certification" | "project" | "work_experience" | "education" | "professional_summary" | "skills" | "achievement" {
    switch (type) {
      case "resume":
        return "work_experience";
      case "project":
        return "project";
      case "skill":
        return "skills";
      case "learning_goal":
        return "professional_summary";
      case "recruiter_conversation":
        return "achievement";
      default:
        return "achievement";
    }
  }
}
